"""add new field in food table

Revision ID: 01d2a15a6792
Revises: 
Create Date: 2024-03-10 01:48:39.203405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01d2a15a6792'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_food_name'), 'food', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_name'), table_name='food')
    op.drop_column('food', 'name')
    # ### end Alembic commands ###
